src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Uid\Uuid;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\HasLifecycleCallbacks]
#[UniqueEntity(fields: ['email'], message: 'Cet email existe déjà au sein de l\'application')]
#[UniqueEntity(fields: ['nickname'], message: 'Ce pseudo existe déjà au sein de l\'application')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\Column(type: 'uuid', unique: true)]
    #[ORM\GeneratedValue(strategy: 'CUSTOM')]
    #[ORM\CustomIdGenerator(class: 'doctrine.uuid_generator')]
    private ?Uuid $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255, unique: true)]
    private ?string $nickname = null;

    #[ORM\Column(length: 255)]
    private ?string $first_name = null;

    #[ORM\Column(length: 255)]
    private ?string $last_name = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $create_at = null;

    #[ORM\Column(length: 255)]
    private ?string $avatar = null;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Article::class, orphanRemoval: true)]
    private Collection $articles;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Like::class, orphanRemoval: true)]
    private Collection $likes;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Comment::class, orphanRemoval: true)]
    private Collection $comments;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $bio = null;

    public function __construct()
    {
        $this->articles = new ArrayCollection();
        $this->likes = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    #[ORM\PrePersist]
    public function prePersist()
    {
        $this->avatar = 'https://api.dicebear.com/7.x/lorelei-neutral/'. $this->email . '.svg';
        $this->avatar = 'https://api.dicebear.com/7.x/lorelei-neutral/svg?seed=' . $this->nickname;
    }

    public function getId(): ?Uuid
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNickname(): ?string
    {
        return $this->nickname;
    }

    public function setNickname(string $nickname): static
    {
        $this->nickname = $nickname;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->create_at;
    }

    public function setCreateAt(\DateTimeInterface $create_at): static
    {
        $this->create_at = $create_at;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(string $avatar): static
    {
        $this->avatar = $avatar;

        return $this;
    }

    /**
     * @return Collection<int, Article>
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): static
    {
        if (!$this->articles->contains($article)) {
            $this->articles->add($article);
            $article->setAuthor($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): static
    {
        if ($this->articles->removeElement($article)) {
            // set the owning side to null (unless already changed)
            if ($article->getAuthor() === $this) {
                $article->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Like>
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(Like $like): static
    {
        if (!$this->likes->contains($like)) {
            $this->likes->add($like);
            $like->setAuthor($this);
        }

        return $this;
    }

    public function removeLike(Like $like): static
    {
        if ($this->likes->removeElement($like)) {
            // set the owning side to null (unless already changed)
            if ($like->getAuthor() === $this) {
                $like->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }

    public function getBio(): ?string
    {
        return $this->bio;
    }

    public function setBio(?string $bio): static
    {
        $this->bio = $bio;

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints\Email;
use Symfony\Component\Validator\Constraints\Regex;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('email', null, [
                'constraints' => [
                    new Email([
                        'message' => 'L\'adresse email "{{ value }}" n\'est pas valide.',
                    ]),
                    new Regex([
                        'pattern' => '/@/',
                        'message' => 'L\'adresse email "{{ value }}" doit contenir le caractère "@".',
                    ]),
                ]
            ])
            ->add('nickname')
            ->add('first_name')
            ->add('last_name')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use App\Repository\CategoryRepository;
use App\Form\ChangePasswordUserFormType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;

#[Route('/user')]
class UserController extends AbstractController
{
    #[Route('/mon-espace', name: 'app_user_index', methods: ['GET'])]
    public function index(CategoryRepository $categoryRepository): Response
    {
        return $this->render('user/index.html.twig', [
            'categories' => $categoryRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_user_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, CategoryRepository $categoryRepository): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('user/new.html.twig', [
            'user' => $user,
            'form' => $form,
            'categories' => $categoryRepository->findAll(),
        ]);
    }

    #[Route('/{id}', name: 'app_user_show', methods: ['GET'])]
    public function show(User $user, CategoryRepository $categoryRepository): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,
            'categories' => $categoryRepository->findAll(),
        ]);
    }

    #[Route('/{id}/edit', name: 'app_user_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, User $user, EntityManagerInterface $entityManager, CategoryRepository $categoryRepository): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();
            $this->addFlash('success', "Les modifications ont bien été enregistré !");
            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'form' => $form,
            'categories' => $categoryRepository->findAll(),
        ]);
    }

    #[Route('/{id}', name: 'app_user_delete', methods: ['POST'])]
    public function delete(Request $request, User $user, EntityManagerInterface $entityManager, CategoryRepository $categoryRepository, TokenStorageInterface $tokenStorage): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $entityManager->remove($user);
            $entityManager->flush();
        }
        $request->getSession()->invalidate();
        $tokenStorage->setToken(null);
        $this->addFlash('success', "Votre compte a été supprimé avec succès.");
        return $this->redirectToRoute('app_app', [
            'categories' => $categoryRepository->findAll(),
        ], Response::HTTP_SEE_OTHER);
    }
    #[Route('/{id}/change-password', name: 'app_user_change_password', methods: ['GET', 'POST'])]
    public function changePassword(Request $request, User $user,UserPasswordHasherInterface $userPasswordHasher, EntityManagerInterface $entityManager, CategoryRepository $categoryRepository): Response
    {
        $form = $this->createForm(ChangePasswordUserFormType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user->setPassword(
                $userPasswordHasher->hashPassword(
                    $user,
                    $form->get('password')->getData()
                )
            );
            $entityManager->persist($user);
            $entityManager->flush();

            $this->addFlash('success', "Le mot de passe a été modifié avec succès !");
            return $this->redirectToRoute('app_user_show', ['id' => $user->getId()]);
        }

        return $this->render('user/change_password.html.twig', [
            'user' => $user,
            'form' => $form,
            'categories' => $categoryRepository->findAll(),
        ]);
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('app_user_delete', {'id': user.id}) }}" onsubmit="return confirm('Êtes-vous sûr de bien vouloir supprimer votre compte ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn btn_filled_red">Supprimer mon compte</button>
</form>

templates/user/_form.html.twig
{{ form_start(form) }}
    <div class="form_container_content-element">
        {{ form_label(form.nickname, 'Pseudo') }}
        {{ form_widget(form.nickname, {
            'attr': {
                'class': 'form_container_content-element-input'
            }
        }) }}
    </div>
    <div class="form_container_content-element">
        {{ form_label(form.first_name, 'Prénom') }}
        {{ form_widget(form.first_name, {
            'attr': {
                'class': 'form_container_content-element-input'
            }
        }) }}
    </div>
    <div class="form_container_content-element">
        {{ form_label(form.last_name, 'Nom') }}
        {{ form_widget(form.last_name, {
            'attr': {
                'class': 'form_container_content-element-input'
            }
        }) }}
    </div>
    <div class="form_container_content-element">
        {{ form_label(form.email, 'Email') }}
        {{ form_widget(form.email, {
            'attr': {
                'class': 'form_container_content-element-input'
            }
        }) }}
    </div>
    <a class="link-golden-darken" href="{{ path('app_user_change_password', {'id': app.user.id})}}">Modifier le mot de passe</a>
    <div class="dashboard_btn_container">
        <button class="btn btn_filled_green text-align-center margin-t-25">{{ button_label|default('Save') }}</button>
    </div>
{{ form_end(form) }}

templates/user/_navbar_dashboard.html.twig
<div class="navbar_dasboard_container">
    <div class="navbar_dashboard_container_element">
        <div class="navbar_dashboard_container_element_item">
            <a href="{{ path('app_user_index')}}" class="navbar_dashboard_container_element_item-link {% if app.request.attributes.get('_route') == 'app_user_index' %}active{% endif %}"><i class="fa-solid fa-house"></i>Mon espace</a>
        </div>
        <div class="navbar_dashboard_container_element_item">
            <a href="{{ path('app_user_show', {'id': app.user.id}) }}" class="navbar_dashboard_container_element_item-link {% if app.request.attributes.get('_route') == 'app_user_show' %}active{% endif %}"><i class="fa-solid fa-user"></i>Mon profil</a>
        </div>   
    </div>
</div>

templates/user/change_password.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification du mot de passe{% endblock %}

{% block body %}
<button id="scrollToTopBtn" class="btn-scroll-to-top">
    <i class="fas fa-arrow-up"></i>
</button>
<div class="dashboard_container">
    {{ include('user/_navbar_dashboard.html.twig') }}
    <div class="dashboard_container_content">
        <h1 class="dashboard_title">Modification du mot de passe</h1>
        {{ form_start(form) }}
            <div class="form_container_content-element">
                {{ form_label(form.password, 'Mot de passe') }}
                {{ form_widget(form.password, {
                }) }}
                <div class="form_container_content-validation-mdp">
                    <p>Votre mot de passe doit contenir 12 caractères minimum:</p>
                    <ul>
                        <li>Une lettre majuscule</li>
                        <li>Une lettre minuscule</li>
                        <li>Un chiffre</li>
                        <li>Un caractère spécial: -+!*$@%_#)</li>
                    </ul>
                </div>
                <div class="form_container_content-error">
                    {{ form_errors(form.password) }}
                </div>
            </div>
            <div class="dashboard_btn_container">
                <button type="submit" class="btn btn_filled_green">Modifier le mot de passe</button>
            </div> 
        {{ form_end(form) }}
    </div>
</div>

{% endblock %}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Dashboard | Modifier mon profil{% endblock %}

{% block body %}
    <button id="scrollToTopBtn" class="btn-scroll-to-top">
        <i class="fas fa-arrow-up"></i>
    </button>
    <div class="dashboard_container">
        {{ include('user/_navbar_dashboard.html.twig') }}
        <div class="dashboard_container_content">
            <h1 class="dashboard_title">Modifier mon profil</h1>
                {{ include('user/_form.html.twig', {'button_label': 'Modifier'}) }}
            <div class="dashboard_btn_container">
                {{ include('user/_delete_form.html.twig') }}
                <a href="{{ path('app_user_show', {'id': app.user.id}) }}" class="btn btn_outlined_golden"><i class="fa-solid fa-arrow-left-long"></i>  Retour à la page précédente</a>
            </div>
        </div>

    </div>

{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Dashboard | Mon espace{% endblock %}

{% block body %}
{% for message in app.flashes('success') %}
    <div class="flash flashy_success">{{ message }}</div>
{% endfor %}
<div class="dashboard_container">
    {{ include('user/_navbar_dashboard.html.twig') }}
    <button id="scrollToTopBtn" class="btn-scroll-to-top">
        <i class="fas fa-arrow-up"></i>
    </button>
    <section class="dashboard_container_content">
        <h1 class="dashboard_title">Mon espace</h1>
            <div class="dashboard_card_container">
                <a class="dashboard_card_content" href="{{ path('app_user_show', {'id': app.user.id}) }}">
                    <ul class="dashboard_list">
                        <li class="dashboard_list-icon"><i class="fa-solid fa-user"></i></li>
                        <li class="dashboard_list-sub-title">Mon profil</li>
                        <li class="dashboard_list-text">Visualisez les informations <br> relative à votre compte</li>
                    </ul>
                </a>
            </div>
    </section>
</div>

{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Dashboard | Mon profil{% endblock %}

{% block body %}
<div class="dashboard_container">
    <button id="scrollToTopBtn" class="btn-scroll-to-top">
        <i class="fas fa-arrow-up"></i>
    </button>
    {{ include('user/_navbar_dashboard.html.twig') }}
    <div class="dashboard_container_content">
        <h1 class="dashboard_title">Mon profil</h1>
        <table class="dashboard_table">
            <tbody class="dashboard_table-tbody">
                <tr>
                    <th>Pseudo</th>
                    <td>{{ user.nickname }}</td>
                </tr>
                <tr>
                    <th>Prénom</th>
                    <td>{{ user.firstName }}</td>
                </tr>
                <tr>
                    <th>Nom</th>
                    <td>{{ user.lastName }}</td>
                </tr>
                <tr>
                    <th>Email</th>
                    <td>{{ user.email }}</td>
                </tr>
            </tbody>
        </table>
        <div class="dashboard_btn_container">
            <a href="{{ path('app_user_edit', {'id': user.id}) }}" class="btn btn_filled_green">Modifier</a>
            {{ include('user/_delete_form.html.twig') }}
            <a href="{{ path('app_user_index') }}" class="btn btn_outlined_golden"><i class="fa-solid fa-arrow-left-long"></i>  Retour à la page précédente</a>
        </div>
    </div>
</div>



{% endblock %}